class ZCL_API_PRINT_DDH definition
  public
  create public .

public section.
    CONSTANTS:
      METHOD_POST TYPE STRING VALUE 'POST',
      METHOD_GET  TYPE STRING VALUE 'GET',
      GC_FAIL     TYPE STRING  VALUE '1',
      GC_SUCCESS  TYPE STRING  VALUE '0'.
    INTERFACES IF_HTTP_SERVICE_EXTENSION .
  PROTECTED SECTION.
  PRIVATE SECTION.
*TYPES
    TYPES: BEGIN OF GTY_REQUEST,
              ebeln TYPE string,
              slin  TYPE string,
              datein  TYPE string,
           END OF GTY_REQUEST.
    DATA: REQUEST_METHOD TYPE STRING,
          REQUEST_BODY   TYPE STRING,
          REQUEST_DATA   TYPE TABLE OF GTY_REQUEST.
*TABLE
    DATA: GT_REQUEST TYPE TABLE OF GTY_REQUEST.
*STRUCTURE
    DATA: GS_RETURN TYPE ZPP_ST_LSX_RESPONSE.
    METHODS PROCESS_DATA.
ENDCLASS.



CLASS ZCL_API_PRINT_DDH IMPLEMENTATION.


    METHOD IF_HTTP_SERVICE_EXTENSION~HANDLE_REQUEST.
    REQUEST_BODY   = REQUEST->GET_TEXT(  ).
    REQUEST_METHOD = REQUEST->GET_METHOD(  ).
    CASE REQUEST_METHOD.
      WHEN METHOD_POST.
        TRY.
            XCO_CP_JSON=>DATA->FROM_STRING( REQUEST_BODY )->APPLY( IT_TRANSFORMATIONS =
        VALUE #( ( XCO_CP_JSON=>TRANSFORMATION->CAMEL_CASE_TO_UNDERSCORE )
                 ( XCO_CP_JSON=>TRANSFORMATION->BOOLEAN_TO_ABAP_BOOL ) )
        )->WRITE_TO( REF #( REQUEST_DATA ) ).
            APPEND LINES OF REQUEST_DATA TO  GT_REQUEST.
            READ TABLE GT_REQUEST INTO DATA(LS_RQ) INDEX 1.
              PROCESS_DATA(  ).
            DATA(LV_JSON_STRING) = XCO_CP_JSON=>DATA->FROM_ABAP( GS_RETURN )->APPLY( VALUE #(
                   ( XCO_CP_JSON=>TRANSFORMATION->UNDERSCORE_TO_PASCAL_CASE ) ) )->TO_STRING( ).

            RESPONSE->SET_TEXT(  I_TEXT = LV_JSON_STRING ).
          CATCH CX_ROOT INTO DATA(LX_ROOT).
            RESPONSE->SET_TEXT( 'Error' ).
        ENDTRY.
    ENDCASE.
  ENDMETHOD.


    METHOD PROCESS_DATA.
    DATA: LS_UPDATE TYPE ztb_mm_ddh,
          LT_UPDATE TYPE TABLE OF  ztb_mm_ddh.
    DATA: LW_ebeln TYPE ebeln.

    LOOP AT GT_REQUEST INTO DATA(LS_REQUEST).
      LW_ebeln   = LS_REQUEST-ebeln.
      LS_UPDATE-ebeln = |{ LW_ebeln ALPHA = IN }|.
      LS_UPDATE-slin   = LS_REQUEST-slin.
      LS_UPDATE-datein   = LS_REQUEST-datein.
      APPEND LS_UPDATE TO LT_UPDATE.

    ENDLOOP.

MODIFY ztb_mm_ddh FROM TABLE @LT_UPDATE.
    IF SY-SUBRC = 0.
      COMMIT WORK AND WAIT.
      APPEND |Update ztb_mm_ddh thành công| TO GS_RETURN-MESSAGE.
      GS_RETURN-RESULT = GC_SUCCESS.
    ELSE.
      GS_RETURN-RESULT = GC_FAIL.
      APPEND |No error| TO GS_RETURN-MESSAGE.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
